exclude: ^\..*
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: end-of-file-fixer
            language: system
        -   id: trailing-whitespace
            language: system
        -   id: check-added-large-files
            language: system
        -   id: check-builtin-literals
            language: system
        -   id: check-case-conflict
            language: system
        -   id: check-json
            language: system
        -   id: pretty-format-json
            language: system
        -   id: check-toml
            language: system
        -   id: check-yaml
            language: system
        -   id: check-xml
            language: system
        -   id: detect-private-key
            language: system
        -   id: name-tests-test
            language: system
        -   id: requirements-txt-fixer
            language: system
#        -   id: double-quote-string-fixer
#            language: system
    -   repo: https://github.com/asottile/pyupgrade
        rev: v1.24.0
        hooks:
        -   id: pyupgrade
            args: [--py3-plus]
            language: system
    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v4.3.21
        hooks:
        - id: isort
          verbose: true
          language: system
# TODO: Does not work on Gitpod
#    -   repo: https://github.com/psf/black
#        rev: stable
#        hooks:
#        - id: black
#          verbose: true
#          language_version: python3.8
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.9
        hooks:
        - id: flake8
          language: system
    -   repo: https://github.com/PyCQA/bandit
        rev: 1.7.0
        hooks:
        - id: bandit
          args: ["-s", "B101,B104"]
          language: system
    -   repo: https://github.com/myint/docformatter
        rev: v1.3
        hooks:
        - id: docformatter
          name: docformatter
          description: 'Formats docstrings to follow PEP 257.'
          entry: docformatter
          args: ['-i','--wrap-summaries=120']
          language: system
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.720
        hooks:
        -   id: mypy
            verbose: true
            entry: bash -c 'mypy "$@" || true' --
            language: system
    -   repo: https://github.com/pycqa/pydocstyle
        rev: 5.1.1  # pick a git hash / tag to point to
        hooks:
        - id: pydocstyle
          args: ["--count"]
          exclude: docs
          language: system
    -   repo: local
        hooks:
        -   id: tests
            name: run tests
            entry: pytest -v
            language: system
            exclude: setup.py
            types: [python]
